### ISSUE TITLE
Add to stackage?

### ISSUE THREAD

**Issue by tmcdonell** [erikd/wide-word#1]
Would you be interested in adding this to stackage? Instructions for adding packages are [here](https://github.com/fpco/stackage/blob/master/MAINTAINERS.md#adding-a-package).

While not a critical package for me, it currently blocks inclusion of `accelerate-bignum` ([see here](https://github.com/fpco/stackage/blob/f2d2e1c7771789199aa5c74343ef73a7ba6cf458/build-constraints.yaml#L684)).

**Comment by erikd** [comment]
I don't use Stackage so I won't be adding it. I have no problem whatsoever with someone else adding it to Stackage.

**Comment by erikd** [comment]
Closing this.
