### ISSUE TITLE
New hackage release?

### ISSUE THREAD

**Issue by neilmayhew** [erikd/wide-word#20]
Any chance of a new hackage release to include recent changes? I'm particularly interested in having [!15](https://github.com/erikd/wide-word/pull/15). Thanks.

**Comment by erikd** [comment]
Will try to get to it this weekend.

**Comment by erikd** [comment]
Version 0.1.0.9 is now on Hackage.

**Comment by neilmayhew** [comment]
Thanks, Erik!
