### ISSUE TITLE
Detect overflow when multiplying large words

### ISSUE THREAD

**Issue by andrewthad** [erikd/wide-word#29]
GHC has a primop `timesWord2` that can be used to detect overflow when multiplying. Or it can be used to actually carry the overflow so that you get a 128-bit number when you multiply two 64-bit numbers. It would be nice to be able to detect overflow when multiplying 128-bit words. (or possibly have an option for carry, but it's overflow that I'm actually concerned about).

**Comment by erikd** [comment]
I see `Word128` as following the `Word8`, `Word16` .... `Word64` convention. None of these provide any way of detecting overflow. If you want overflow detection, it sounds like you want `Natural` instead of `Word128`.

**Comment by andrewthad** [comment]
The analogy argument makes sense to me. Closing.

> If you want overflow detection, it sounds like you want `Natural` instead of `Word128`.

This is not the case. `Natural` is a rather expensive way to detect overflow. It should be possible to detect multiplication overflow without performing any allocations.
