### ISSUE TITLE
Unpack record fields

### ISSUE THREAD

**Issue by nosewings** [erikd/wide-word#54]
Is there any reason not to add `UNPACK` pragmas to record fields? This seems like an obvious and simple way to gain some performance.

**Comment by lehins** [comment]
@nosewings see #43 for related ticket. I personally prefer `UNPACK` too, but the author chose not to because they aren't really needed. In reality, even the flag `-funbox-strict-fields` not needed, ghc will unpack those automatically as part of optimizations.

**Comment by erikd** [comment]
@lehins is correct. I prefer a single `-funbox-strict-fields` at the top of each file rather than an `UNPACK` pragma on all the fields.

**Comment by erikd** [comment]
When I drop support for `ghc < 8.0` I will likely switch to the `StrictData` pragma instead.

**Comment by lehins** [comment]
@erikd technically even `-funbox-strict-fields` isn't needed because `-funbox-small-strict-fields` is on by default, but I often tend prefer to be more specific with annotations, even if it means being more verbose.

**Comment by chessai** [comment]
Can this be closed?
