### ISSUE TITLE
Build with GHC 9.0

### ISSUE THREAD

**Issue by andrewthad** [erikd/wide-word#55]
This might be as simple as relaxing the upper bound on base.

**Comment by erikd** [comment]
I think I fixed this on the weekend and I updated the Hackage metadata. Please try `cabal update`.

**Comment by andrewthad** [comment]
Hackage shows

    base (>=4.9 && <4.15)

for the latest `wide-word`, and it doesn't indicate that there have been any revisions. You may have accidentally hit "preview" instead of "release". I've done that several times before.

**Comment by erikd** [comment]
Sorry, was looking at the wrong package.

I have updated the bounds on Hackage, but I can't build it due to `hashable => base>=4.5 && <4.15`.

**Comment by andrewthad** [comment]
Awesome, thanks! I'm sure `hashable` will get updated any day now.
