### ISSUE TITLE
extra instances

### ISSUE THREAD

**Issue by infinity0** [erikd/wide-word#56]
Hi, thanks for creating this package. I needed some extra instances so I went ahead and defined them and uploaded it to hackage: https://hackage.haskell.org/package/wide-word-instances-0.1

If you'd like to merge those into this repo or co-maintain them or something, just let me know, I will be happy to add you to the hackage owners group.

**Comment by erikd** [comment]
I can't see any good reason why these instances should not be provided by `wide-word` itself. Please submit a PR.

**Comment by infinity0** [comment]
I was thinking it might be good to try to have this added to GHC base libraries, e.g. like how rust provides 128 and 256-bit integers. In this case, these instances would have to go in their respective packages `binary` and `serialise`.

**Comment by phadej** [comment]
I think `Binary` belongs to `wide-word` (See also #50). `serialize` OTOH starts to be a heavier package, so it makes more sense for `serialise` to depend on` wide-word`, and I don't see a reason why it wouldn't.

**Comment by phadej** [comment]
To clarify my stance on `serialise` instances.

I'm considering adding `wide-word` dependency to e.g. `aeson`. But if there is even a slightest chance (or risk) that `wide-word` would depend on `serialise`, then I cannot afford that.

The current dependency footprint of `wide-word` is acceptable, but depending on libraries which itself depend on a lot of packages (like `serialise` is a batteries-included one depending on plenty of small type providing libs) won't be.
