### ISSUE TITLE
`base` is 4.16.x in 9.2.1; `wide-word` includes `<4.16` in published build

### ISSUE THREAD

**Issue by Dessix** [erikd/wide-word#66]
~~It appears `9.2` is in the CI parameters- is this just a matter of bumping the bounds in the cabal spec?~~

Looks like it's just the current build on hackage being out of date; a release should fix this for 9.2.1 users.

**Comment by erikd** [comment]
I just updated the Hackage metadata.

Try `cabal update` and then rebuild.

**Comment by Dessix** [comment]
Mutating an existing version's metadata works on Hackage? Nonetheless- looks good to close.

**Comment by erikd** [comment]
Yes, should just work. I was leaving this open until you could confirm that.

**Comment by Dessix** [comment]
It does work in that I was able to include it as a dependency successfully. Unfortunately there are [a lot of other items that need changed](/airalab/hs-web3/issues/125#issuecomment-1038565792) before I can confirm more than the unit tests would.

**Comment by erikd** [comment]
Right, but `wide-word` now builds so this is fixed from the point of view of this package. So this ticket can be closed right?

**Comment by erikd** [comment]
Thanks!
