### ISSUE TITLE
Allow building with hedgehog == 1.1.*

### ISSUE THREAD

**Issue by sternenseemann** [erikd/wide-word#71]
This has been confirmed to work fine by me, so the bound on hedgehog can be changed to `>= 1.0 && < 1.2` safely. Publishing a hackage revision for this would be useful to us! Tested build and execution of the test suite for `wide-word-0.1.1.2` from hackage.

**Comment by erikd** [comment]
Currently working on `ghc-9.4` support and that will be resolved at the same time.

**Comment by erikd** [comment]
This should be fixed with the latest `0.1.3.0` release on Hackage which also supports `ghc-9.2`.
