### ISSUE TITLE
Add QuickCheck instances

### ISSUE THREAD

**Issue by phadej** [erikd/wide-word#77]
`QuickCheck` is quite a small, stable and universally used library. It would be great if `wide-word` had quickcheck instances.

An alternative is to add `wide-word` instances to `quickcheck-instances`, but then I'd need a guarantee that `wide-word` wont' acquire extra dependencies.

**Comment by erikd** [comment]
I prefer the idea of:

> An alternative is to add `wide-word` instances to `quickcheck-instances`, 

I am also not keen on adding any large dependencies to `wide-word`.

**Comment by phadej** [comment]
@erikd good. I'll add `wide-word` instances to `quickcheck-instances` at some point soon (probably when upgrading it for GHC-9.6).

**Comment by erikd** [comment]
Decided that Quickeck instances willnot be added.
