### ISSUE TITLE
Make the `shift` functions `INLINEABLE`

### ISSUE THREAD

**Issue by michaelpj** [erikd/wide-word#81]
Currently marked as "Probably not worth inlining this": https://github.com/erikd/wide-word/blob/master/src/Data/WideWord/Word128.hs#L327

However, it's quite common to shift something by a constant. Then inlining is great: you can narrow down to a single branch, maybe further inline the RHS, and perhaps even avoid allocating when returning.

**Comment by erikd** [comment]
Won't inlining these mean the conditional will also be inlined (in the case where the shift amount is not a constant).

**Comment by erikd** [comment]
Although `INLINEABLE` does not force inlining, so it should be ok.
